terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# -----------------------------------------------------------------
# AMI: latest Amazon Linux 2023 (x86_64)
# -----------------------------------------------------------------
data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# -----------------------------------------------------------------
# Ephemeral deploy key — generated by Terraform, no passphrase.
# NOTE: the private key is stored in Terraform state. Keep state
# secure (e.g. remote backend with encryption) in production.
# -----------------------------------------------------------------
resource "tls_private_key" "deploy" {
  algorithm = "ED25519"
}

resource "local_sensitive_file" "deploy_private_key" {
  filename        = abspath("${path.module}/../.deploy_key")
  content         = tls_private_key.deploy.private_key_openssh
  file_permission = "0600"
}

resource "aws_key_pair" "this" {
  key_name   = var.key_name
  public_key = tls_private_key.deploy.public_key_openssh
}

# -----------------------------------------------------------------
# Security group — SSH open to the world
# -----------------------------------------------------------------
resource "aws_security_group" "ssh" {
  name        = "tf-ansible-ssh"
  description = "Allow SSH from anywhere"

  ingress {
    description      = "SSH"
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  egress {
    description      = "All outbound"
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  tags = {
    Name = "tf-ansible-ssh"
  }
}

# -----------------------------------------------------------------
# EC2 instance — t3.micro (free-tier eligible)
# -----------------------------------------------------------------
resource "aws_instance" "this" {
  ami                         = data.aws_ami.al2023.id
  instance_type               = "t3.micro"
  key_name                    = aws_key_pair.this.key_name
  vpc_security_group_ids      = [aws_security_group.ssh.id]
  associate_public_ip_address = true

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 8
    delete_on_termination = true
  }

  tags = {
    Name = "tf-ansible-minimal"
  }

  # Recreate the instance whenever the deploy key changes so the new
  # public key is baked in via cloud-init at launch.
  lifecycle {
    replace_triggered_by = [tls_private_key.deploy]
  }
}

# -----------------------------------------------------------------
# Generate Ansible inventory so `ansible-playbook` works immediately
# -----------------------------------------------------------------
resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/hosts.ini"
  file_permission = "0644"
  content         = <<-INI
    [managed]
    ${aws_instance.this.public_ip} ansible_user=ec2-user ansible_ssh_private_key_file=${local_sensitive_file.deploy_private_key.filename}

    [managed:vars]
    managed_user=${var.managed_user}
    managed_user_public_key=${jsonencode(var.managed_user_public_key)}
  INI
}
